staging-settings:
  user-workflow:
    workflow-name: new-one
  workflow-artifacts:
    workflow-path: ./main.ts
    config-path: ./config.staging.json
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
production-settings:
  user-workflow:
    workflow-name: new-one
  workflow-artifacts:
    workflow-path: ./main.ts
    config-path: ./config.production.json
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
